Daskata/Controllers/AnswerController.cs
using Daskata.Core.Contracts.Answer;
using Daskata.Core.ViewModels;
using Daskata.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Daskata.Controllers
{
    public class AnswerController : Controller
    {
        private readonly UserManager<UserProfile> _userManager;
        private readonly ILogger<AnswerController> _logger;
        private readonly IAnswerService _answerService;

        public AnswerController(UserManager<UserProfile> userManager,
            ILogger<AnswerController> logger,
            IAnswerService answerService)
        {
            _userManager = userManager;
            _logger = logger;
            _answerService = answerService;
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Answer/{parentExamUrl}/{parentQuestionId}/Add")]
        [HttpGet]
        public async Task<IActionResult> Add(Guid parentQuestionId)
        {
            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            try
            {
                var model = await _answerService.PrepareAnswerForCreationAsync(parentQuestionId, loggedUser.Id);

                if (model == null)
                {
                    return NotFound();
                }

                return View(model);
            }

            catch (InvalidOperationException ex)
            {
                _logger.LogError(ex, "Answer not found.");

                return NotFound();
            }

            catch (UnauthorizedAccessException ex)
            {
                _logger.LogError(ex, "Unauthorized attempt to open an answer.");

                return Unauthorized();
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Answer/{parentExamUrl}/{parentQuestionId}/Add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(string parentExamUrl, Guid parentQuestionId, AnswerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            try
            {
                await _answerService.AddAnswerAsync(model, parentQuestionId, loggedUser.Id);

                _logger.LogInformation($"Answer with Id {model.Id} was successfully created");

                return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl, id = parentQuestionId });
            }

            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return View(model);
            }

            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return View(model);
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Answer/{parentExamUrl}/{parentQuestionId}/{answerId}/Edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid answerId)
        {
            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            try
            {
                var model = await _answerService.GetAnswerForEditAsync(answerId, loggedUser.Id);
                if (model == null)
                {
                    return NotFound();
                }
                return View(model);
            }

            catch (InvalidOperationException ex)
            {
                _logger.LogError(ex, "Answer not found.");

                return NotFound();
            }

            catch (UnauthorizedAccessException ex)
            {
                _logger.LogError(ex, "Unauthorized attempt to edit an answer.");

                return Unauthorized();
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Answer/{parentExamUrl}/{parentQuestionId}/{answerId}/Edit/")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string parentExamUrl, Guid parentQuestionId, 
            Guid answerId, AnswerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            try
            {
                await _answerService.EditAnswerAsync(model, answerId, loggedUser.Id);

                _logger.LogInformation($"Answer with Id {answerId} was successfully edited");

                return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl, id = parentQuestionId });
            }

            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return View(model);
            }

            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return View(model);
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Answer/{parentExamUrl}/{parentQuestionId}/{answerId}/Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete (string parentExamUrl, Guid parentQuestionId, Guid answerId)
        {
            try
            {
                var userId = (await _userManager.GetUserAsync(User))?.Id;

                if (userId == null)
                {
                    return Unauthorized();
                }

                await _answerService.DeleteAnswerAsync(answerId, userId.Value);

                _logger.LogInformation($"Answer with Id {answerId} was successfully deleted.");
                return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl, id = parentQuestionId });
            }

            catch (InvalidOperationException ex)
            {
                _logger.LogError(ex, "Отговорът не е намерен.");
                return NotFound();
            }

            catch (UnauthorizedAccessException ex)
            {
                _logger.LogError(ex, "Потребителят няма права да изтрие отговора.");
                return Unauthorized();
            }
        }
    }
}

Daskata/Controllers/QuestionController.cs
using Daskata.Core.Contracts.Question;
using Daskata.Core.ViewModels;
using Daskata.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Daskata.Controllers
{
    [Authorize]
    public class QuestionController : Controller
    {
        private readonly UserManager<UserProfile> _userManager;
        private readonly ILogger<QuestionController> _logger;
        private readonly IQuestionService _questionService;

        public QuestionController (UserManager<UserProfile> userManager,
            ILogger<QuestionController> logger,
            IQuestionService questionService)
        {
            _userManager = userManager;
            _logger = logger;
            _questionService = questionService;
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Question/{parentExamUrl}/Create")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var parentExamUrl = TempData["ExamQuestionUrl"];

            var model = await _questionService.PrepareQuestionForCreationAsync(parentExamUrl!.ToString()!);

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [HttpPost]
        [Route("/Question/{parentExamUrl}/Create")]
        public async Task<IActionResult> Create(QuestionViewModel model, string parentExamUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try

            {
                await _questionService.CreateQuestionAsync(model, parentExamUrl);

                _logger.LogInformation("New question was created for the exam URL: {parentExamUrl}", parentExamUrl);
            }
            catch (ArgumentException ex)
            {
                _logger.LogError(ex, "Error creating question: Exam not found for URL: {parentExamUrl}", parentExamUrl);
                ModelState.AddModelError(string.Empty, "Търсеният изпит не беше намерен.");
                return View(model);
            }

            return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl });
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Question/{parentExamUrl}/{questionId}/Edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid questionId)
        {
            var parentExamId = TempData["ExamQuestionId"] as Guid?;

            if (parentExamId == null)
            {
                return NotFound();
            }

            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            try
            {
                var model = await _questionService.GetQuestionForEditAsync(questionId, loggedUser.Id);
                return View(model);
            }
            catch (InvalidOperationException ex)
            {
                return NotFound(ex.Message);
            }
            catch (UnauthorizedAccessException ex)
            {
                return Unauthorized(ex.Message);
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [HttpPost]
        [Route("/Question/{parentExamUrl}/{questionId}/Edit")]
        public async Task<IActionResult> EditQuestion(QuestionViewModel model, string parentExamUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var result = await _questionService.UpdateQuestionAsync(model, parentExamUrl);

                if (!result)
                {
                    return NotFound();
                }

                _logger.LogInformation($"Question with Id {model.Id} was successfully edited.");
                return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl });
            }
            catch (KeyNotFoundException ex)
            {
                _logger.LogError(ex, ex.Message);
                return NotFound(ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred when trying to update the question.");
                ModelState.AddModelError(string.Empty, "Възникна неочаквана грешка по време на актуализиране на въпроса.");
                return View(model);
            }
        }

        [Authorize(Roles = "Admin,Manager,Teacher")]
        [Route("/Question/{parentExamUrl}/{questionId}/Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(string parentExamUrl, Guid questionId)
        {
            var loggedUser = await _userManager.GetUserAsync(User);

            if (loggedUser == null)
            {
                return Unauthorized();
            }

            var result = await _questionService.DeleteQuestionAsync(questionId, loggedUser.Id);

            if (!result)
            {
                return NotFound();
            }

            _logger.LogInformation($"Question with Id {questionId} was successfully deleted.");

            return RedirectToAction("Open", "Exam", new { examUrl = parentExamUrl });
        }
    }
}

Daskata/Views/Exam/All.cshtml
@using static Daskata.Core.Shared.Methods;
@model ExamListViewModel

@{
    ViewData["Title"] = "Всички изпити";
}

<div class="container mt-5 floor">
    <div class="row page-title-box align-items-center">
        <div class="col-sm-6">
            <h1 class="p-3" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">Всички изпити</h1>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <a asp-area="" asp-controller="Exam" asp-action="All" class="btn btn-primary w-100 button-title">Всички изпити</a>
                </div>
                <div class="col-sm-12">
                    <a asp-area="" asp-controller="Exam" asp-action="My" class="btn btn-primary w-100 button-title">Моите изпити</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row page-title-box align-items-center">
        <div class="row">
            <div class="col-12">
                <form asp-controller="Exam" asp-action="All" method="get" class="mb-4 pt-4">
                    <div class="row align-items-center">
                        <div class="col-md-10 col-12">
                            <input type="text" class="form-control profile-edit-input" placeholder="Търсене..." asp-for="@Model.Keyword">
                        </div>
                        <div class="col-md-2 col-12 mt-md-0 mt-2">
                            <button type="submit" class="btn btn-primary w-100 button-title">Търси</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <form asp-controller="Exam" asp-action="All" method="get" class="mb-4">
                    <div class="row align-items-center">
                        <div class="col-md-3 col-12 mt-2">
                            <select class="form-control profile-edit-input" asp-for="@Model.SubjectCategory" asp-items="ViewBag.SubjectCategories">
                                <option value="">Изберете категория</option>
                                <option value="Mathematics">Математика</option>
                                <option value="BulgarianLanguage">Български език</option>
                                <option value="Literature">Литература</option>
                                <option value="History">История</option>
                                <option value="Biology">Биология</option>
                                <option value="Chemistry">Химия</option>
                                <option value="Physics">Физика</option>
                                <option value="Geography">География</option>
                                <option value="EnglishLanguage">Английски език</option>

                            </select>
                        </div>
                        <div class="col-md-3 col-12 mt-2">
                            <select class="form-control profile-edit-input" asp-for="@Model.GradeCategory" asp-items="ViewBag.GradeCategories">
                                <option value="">Изберете клас</option>
                                <option value="Grade1">Първи клас</option>
                                <option value="Grade2">Втори клас</option>
                                <option value="Grade3">Трети клас</option>
                                <option value="Grade4">Четвърти клас</option>
                                <option value="Grade5">Пети клас</option>
                                <option value="Grade6">Шести клас</option>
                                <option value="Grade7">Седми клас</option>
                                <option value="Grade8">Осми клас</option>
                                <option value="Grade9">Девети клас</option>
                                <option value="Grade10">Десети клас</option>
                                <option value="Grade11">Единадесети клас</option>
                                <option value="Grade12">Дванадесети клас</option>
                            </select>
                        </div>
                        <div class="col-md-2 col-12 mt-2">
                            <input type="date" class="form-control profile-edit-input" asp-for="@Model.DateFromFilter" placeholder="От дата">
                        </div>
                        <div class="col-md-2 col-12 mt-2">
                            <input type="date" class="form-control profile-edit-input" asp-for="@Model.DateToFilter" placeholder="До дата">
                        </div>
                        <div class="col-md-2 col-12 mt-2">
                            <button type="submit" class="btn btn-primary w-100 button-title">Филтрирай</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        @foreach (var exam in Model.Exams)
        {
            if (exam != null & exam!.IsPublished)
            {
                <div class="exam-box" onclick="previewExam('@exam.ExamUrl')">
                    <div class="exam-status-eye all">@await Html.PartialAsync(exam.IsPublic ? "_PublicEyePartial" : "_PrivateEyePartial")</div>
                    <p><span class="exam-title">@exam.Title</span></p>
                    <p><span class="exam-description">@exam.Description</span></p>
                    <div class="exam-box-inner">
                        <div class="exam-box-sub"><span class="exam-sub-text">⌛ @exam.Duration мин</span></div>
                        <div class="exam-box-sub"><span class="exam-sub-text">✍️ @exam.TotalPoints т.</span></div>
                        <div class="exam-box-sub"><span class="exam-sub-text">📅 @GetRegistrationMonthYearAsNumbers(exam.CreationDate.ToString())</span></div>
                    </div>
                </div>
            }
        }
    </div>
    <div class="pagination-container mt-4 mb-4 text-center">
        @if (Model.Exams.HasPreviousPage)
        {
            <a asp-action="All" asp-route-pageNumber="@(Model.CurrentPage - 1)" class="btn btn-default">Предишна</a>
        }
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            if (i == Model.CurrentPage)
            {
                if (Model.CurrentPage == 1 && Model.TotalPages == 1)
                {
                    <span></span>
                }
                else
                {
                    <span class="current-page">@i</span>
                }   
            }
            else
            {
                <a asp-action="All" asp-route-pageNumber="@i" class="btn btn-default">@i</a>
            }
        }
        @if (Model.Exams.HasNextPage)
        {
            <a asp-action="All" asp-route-pageNumber="@(Model.CurrentPage + 1)" class="btn btn-default">Следваща</a>
        }
    </div>
</div>

@section Scripts {
    <script src="~/js/reduce-title-description.js"></script>
    <script src="~/js/preview-id-fetch.js"></script>
}

Daskata/Views/Exam/Create.cshtml
@using static Daskata.Core.Shared.Methods
@model List<string>

@{
    ViewData["Title"] = "Създаване на изпит";
}

<div class="home-container-column mt-5">
    <h2 class="mt-4 text-center">Стъпка 1/3 : Избери предмет</h2>
    <div class="row">
        <form asp-controller="Exam" asp-action="Grade" method="post">
            <input type="hidden" id="subjectInput" name="subject" value="@ViewData["Subject"]" />
            <div class="exam-preview">
                <div class="form-group">
                    <div class="row justify-content-center">
                        @foreach (var subject in Model)
                        {
                            if (subject != null && subject != "Undefied")
                            {
                                <div class="col">
                                    <button type="button" class="btn btn-primary button-create-test subject-button m-2" data-value="@subject">@TranslateExamSubjectInBG(subject)</button>
                                </div>
                            }
                        }
                    </div>
                </div>
                
            </div>
            <div class="mt-5 text-center">
                <a asp-controller="Exam" asp-action="All" type="submit" class="btn btn-primary button-create-user">Назад</a>
                <button type="submit" class="btn btn-primary button-create-user" id="submitButton">Напред</button>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script src="~/js/hide-next-subject.js"></script>
}

Daskata/Views/Exam/Open.cshtml
@using Daskata.Infrastructure.Data
@using Daskata.Infrastructure.Data.Models
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@using static Daskata.Core.Shared.Methods;
@inject DaskataDbContext _context
@model FullExamViewModel;
@inject UserManager<UserProfile> _userManager

@{
    ViewData["Title"] = "Изпит";
    var userId = @Model.CreatedByUserId.ToString();
    var createdByUser = await _userManager.FindByIdAsync(userId);
    var loggedUser = await _userManager.GetUserAsync(User);
}

<div class="home-container-column">
    <div class="row">
        <div class="exam-preview open">
            <h2 class="mb-5 mt-3 text-center">@Model.Title</h2>
            <p class="mb-5">@Model.Description</p>
            <div class="row text-center" style="font-size: 15px; color:#424242">
                <div class="col-md-6">
                    <p class="m-0">Предмет: @TranslateExamSubjectInBG(Model.StudySubject.ToString())</p>
                    <p class="m-0">Подходяща възраст: @GradeNumberExtract(Model.StudentGrade.ToString()) клас</p>
                </div>
                <div class="col-md-6 mb-5">
                    <p class="m-0">Продължителност: @Model.Duration мин</p>
                    <p class="m-0">Максимален брой точки: @Model.TotalPoints</p>
                </div>
            </div>
            @{
                if (userId == loggedUser!.Id.ToString())
                {
                    bool warningFlag = Model.Questions.Count() == 0
                    || ((Model.TotalPoints > ViewBag.TotalQuestionsPoints
                    || Model.TotalPoints < ViewBag.TotalQuestionsPoints)
                    && Model.Questions.Count() > 0)
                    || ViewBag.HasQuestionWithoutAnswer;

                    if (warningFlag)
                    {
                        <div class="exam-warning-box">
                            <h5 class="mb-3 text-center">Внимание!</h5>
                            @if (Model.Questions.Count() == 0)
                            {
                                <p class="mb-3">
                                    Вашият изпит все още няма формулирани въпроси. Моля, добавете въпроси, за да стане активен.
                                </p>
                            }
                            @if ((Model.TotalPoints > ViewBag.TotalQuestionsPoints
                                || Model.TotalPoints < ViewBag.TotalQuestionsPoints)
                                && Model.Questions.Count() > 0)
                            {
                                <p class="mb-3">
                                    Изпитът е определен с максимален брой точки @Model.TotalPoints, докато общият брой точки от въпросите е @ViewBag.TotalQuestionsPoints. За да бъде активен и достъпен за решаване, двете стойности трябва да са равни.
                                </p>
                            }
                            @if (ViewBag.HasQuestionWithoutAnswer)
                            {
                                <p class="mb-3">
                                    Във вашия изпит имате въпрос, който няма отговори. За да е активен и достъпен за решаване не следва да има въпрос без зададени отговори.
                                </p>
                            }
                        </div>
                    }
                    else
                    {
                        <div class="exam-success-box">
                            <h5 class="mb-3 text-center">Поздравления!</h5>
                            <p class="mb-3 text-center">Вашият изпит може да бъде активиран.</p>
                        </div>
                    }
                }
            }

            @if (Model.Questions.Any())
            {
                <ol>
                    @foreach (var question in Model.Questions)
                    {
                        <li>
                            <div class="d-flex justify-content-between align-items-start">
                                <div>
                                    <p><strong>@question.QuestionText</strong></p>
                                    @if (!string.IsNullOrEmpty(question.Explanation))
                                    {
                                        <p style="font-size: 15px;">Допълнително пояснение: @question.Explanation</p>
                                    }
                                    <div class="col-md-12">
                                        <p class="m-0">Брой точки: <span>@question.Points т.</span></p>
                                        <p class="m-0">Тип: <span>@TranslateQuestionsTypeBG(question.QuestionType)</span></p>
                                        <p class="m-0">Верни отговори: @(question.IsMultipleCorrect ? "Няколко" : "Един")</p>
                                    </div>
                                    <div class="col-md-12 mt-3 mb-3">
                                        <p><strong>Отговори:</strong></p>
                                        @{
                                            var random = new Random();
                                            bool isUnderExam = true;
                                            var answers = isUnderExam ? question.Answers.ToList() : question.Answers.OrderBy(a => random.Next()).ToList();
                                            char letter = 'а';
                                        }

                                        @foreach (var answer in answers)
                                        {
                                            <div class="d-flex align-items-center @(answer.IsCorrect ? "correct-answer" : "")">
                                                @if (createdByUser == loggedUser)
                                                {
                                                    <a href="/Answer/@Model.ExamUrl/@question.Id/@answer.Id/Edit" class="text-decoration-none">
                                                        <img src="~/lib/edit-answer.png" width="24px" />
                                                    </a>
                                                    <form class="delete-answer" asp-controller="Answer" asp-action="Delete" method="post"
                                                          asp-route-parentExamUrl="@Model.ExamUrl" asp-route-parentQuestionId="@question.Id" asp-route-answerId="@answer.Id">
                                                        @Html.AntiForgeryToken()
                                                        <button type="submit" class="border-0 p-0 m-2" style="background-color: transparent" alt="Delete Answer">
                                                            <img src="~/lib/remove-answer.png" width="24px" />
                                                        </button>
                                                    </form>
                                                }
                                                <p class="mb-0">@letter/. @answer.AnswerText</p>
                                            </div>
                                            letter++;
                                        }
                                    </div>
                                </div>
                                @if (createdByUser == loggedUser)
                                {
                                    <div class="d-flex flex-column align-items-end justify-content-start">
                                        <a href="/Question/@Model.ExamUrl/@question.Id/Edit" class="m-2" alt="Редактиране на въпрос">
                                            <partial name="_EditButtonSVGPartial" />
                                        </a>
                                        <form class="delete-question border-0 p-0" asp-controller="Question" asp-action="Delete" method="post" asp-route-questionId="@question.Id" asp-route-parentExamUrl="@Model.ExamUrl">
                                            <input type="hidden" name="questionId" value="@question.Id" />
                                            <input type="hidden" name="parentExamUrl" value="@Model.ExamUrl" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="border-0 p-0 m-2" style="background-color: transparent" alt="Изтриване на въпрос">
                                                <partial name="_DeleteButtonSVGPartial" />
                                            </button>
                                        </form>
                                    </div>
                                }
                            </div>
                            <div>
                                @if (createdByUser == loggedUser)
                                {
                                    <a href="/Answer/@Model.ExamUrl/@question.Id/Add" class="text-decoration-none"><img src="~/lib/add-answer.png" width="30px" /> </a>
                                }
                            </div>
                            <hr />
                        </li>
                    }
                </ol>
            } 
            @{
                if (userId == loggedUser!.Id.ToString())
                {
                    <div class="exam-preview-button">
                        <a href="/Question/@Model.ExamUrl/Create" class="button-create-test btn btn-primary d-flex justify-content-center align-items-center m-0">Добави въпрос</a>
                    </div>
                    <div class="exam-preview-button">
                        <a asp-area="" asp-controller="Exam" asp-action="Asign" class="button-create-test btn btn-primary d-flex justify-content-center align-items-center m-0">Изпрати до ученик</a>
                    </div>
                    <div class="exam-preview-button">
                        <a href="/Exam/Preview/@Model.ExamUrl/" class="button-create-test btn btn-primary d-flex justify-content-center align-items-center m-0">Назад</a>
                    </div>
                }
                else
                {
                    <div class="exam-preview-button">
                        <a asp-area="" asp-controller="Exam" asp-action="Asign" class="button-create-test btn btn-primary d-flex justify-content-center align-items-center m-0">Изпрати до ученик</a>
                    </div>
                    <div class="exam-preview-button">
                        <a href="/Exam/Preview/@Model.ExamUrl/" class="button-create-test btn btn-primary d-flex justify-content-center align-items-center m-0">Назад</a>
                    </div>
                }
            }
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/js/user-profile-fetch.js"></script>
    <script src="~/js/question-answer-notification.js"></script>
}